### ISSUE TITLE
Missing [super viewDidLoad] call

### ISSUE THREAD

**Issue by ksm** [mtrudel/MTGenericSemimodalSegue#2]
Hi Mat!

In `MTSemimodalHostingViewController -viewDidLoad` ([line 14](https://github.com/mtrudel/MTGenericSemimodalSegue/blob/master/Classes/ios/MTSemimodalHostingViewController.m#L14)) there's a missing call to to `[super viewDidLoad]`. Is that on purpose or is that an omission? Found this with Xcode's static analyzer.

**Comment by mtrudel** [comment]
It's a bug. I actually fixed it in a private branch ages ago and forgot to push it up here. Will do so in the next day.

**Comment by mtrudel** [comment]
Fixed in 7264eca (pushed to Cocoapods as 0.0.20).

Thanks for the heads up!

**Comment by ksm** [comment]
Thanks!
